-
  name: Docker Install + container + hashsvccli
  hosts: group1
  become: yes # become_user: root
  roles:
    - docker
    - container


-
  name: hashsvccli
  hosts: group2
  become: yes # become_user: root
  roles:
    - hashsvccli
