- name: Install pip
  tags: install_pip
  apt: name=python3-pip state=present

- name: Install python modules for docker
  tags: install_python_modules
  pip:
    name: "{{item.name}}"
    executable: pip3
    version: "{{item.version}}"
    state: present
  with_items:
  - { name: docker, version: 2.0.0 }
  - { name: docker-py, version: 1.10.6 }

- name: Creates directory ~/hashapp
  file:
    path: ~/hashapp
    state: directory

- name: Download du dockerfile et requirement.txt
  get_url:
    url: "{{item.url1}}"
    dest: "{{item.dest1}}"
  with_items:
    - { url1: "https://github.com/gb-0001/j9-tp/raw/master/src_dockerfile/Dockerfile" , dest1: "~/hashapp/Dockerfile" }
    - { url1: "https://github.com/gb-0001/j9-tp/raw/master/src_dockerfile/requirements.txt" , dest1: "~/hashapp/requirements.txt" }
    - { url1: "https://github.com/gb-0001/j9-tp/raw/master/src_microsvc/main.py" , dest1: "~/hashapp/main.py" }

- name: build image
  tags: build_image
  docker_image:
    path: ~/hashapp
    name: hashappdck:latest
    state: present

- name: start image
  tags: start_image
  docker_container:
    name: "{{item.name}}"
    image: hashappdck:latest
    state: started
    forcekill: yes
    ports:
      - "{{item.portn}}:5000"
  with_items:
    - { name: hashapp1 , portn: 3001 }
    - { name: hashapp2 , portn: 3002 }
    - { name: hashapp3 , portn: 3003 }
