- name: Installation unzip
  yum:
    name: "{{item}}"
    state: present
    disable_gpg_check: yes
    update_cache: true
  with_items:
    - unzip
    - python
    - python3-pip
    - httpd

- name: Creates directory ~/hashsvccli
  become: no
  file:
    path: ~/hashsvccli
    state: directory

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: https://opusidea-training.s3.eu-west-3.amazonaws.com/divers/hashservice-client.zip
    dest: ~/hashsvccli
    remote_src: yes

- name: permit traffic in default zone for http service
  firewalld:
    service: http
    permanent: yes
    immediate: yes
    state: enabled

- name: copie des sources dans /var/www/html
  copy:
    src: "{{item}}"
    dest: /var/www/html/
    owner: apache
    group: apache
    mode: '0644'
    remote_src: yes
  with_items:
    - ~/hashsvccli/hashservice-client/index.html
    - ~/hashsvccli/hashservice-client/index.js


# - name: mise a jour de l'ip
#   lineinfile:
#     dest: /var/www/html/index.js
#     regexp: ^API_URL = "http://localhost:3000/"
#     line: "API_URL = "http://{{'ansible_host'}}:3000/""


- name: start service
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - "httpd"
